#!/usr/bin/env sh

_() {
  read -p "Set year(default 1990): " YEAR
          if [ -z "$YEAR" ];then
          YEAR="1990"
          fi
  read -p "GitHub Username: " USERNAME
  read -p "GitHub Access token: " ACCESS_TOKEN

  [ -z "$USERNAME" ] && exit 1
  [ -z "$ACCESS_TOKEN" ] && exit 1
  [ ! -d $YEAR ] && mkdir $YEAR

 echo "created ${YEAR}/"

  cd "${YEAR}" || exit
  git init
  echo "**${YEAR}** - Generated by https://github.com/talentestors/1991-script" \
    >README.md
  git add .
  GIT_AUTHOR_DATE="${YEAR}-01-01T18:00:00" \
    GIT_COMMITTER_DATE="${YEAR}-01-01T18:00:00" \
    git commit -m "${YEAR}"
  git remote add origin "https://${ACCESS_TOKEN}@github.com/${USERNAME}/${YEAR}.git"
  git branch -M main
  git push -u origin main -f
  cd ..
  rm -rf "${YEAR}"

  echo
  echo "Cool, check your profile now: https://github.com/${USERNAME}"
} && _

unset -f _
